// components/CistercianMonkNumerals/Numeral.tsx
import { Image } from "../Image";

export interface DigitProps {
  value: string;
  strokeLinecap?: string;
  strokeWidth: number;
  width: number;
  height: number;
  scale?: number;
}

const MAG_XY = {
  ones: [1, -1],
  tens: [-1, -1],
  hundreds: [1, 1],
  thousands: [-1, 1],
};

export function svgStrForVal(val: string, mag: keyof typeof MAG_XY): string {
  const [x, y] = MAG_XY[mag];

  switch (val) {
    case "1": {
      return `<line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 1.5}cm"
            y2="${2 + y * 1.5}cm"
          />`;
    }
    case "2": {
      return `<line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 0.5}cm"
            y2="${2 + y * 0.5}cm"
          />`;
    }
    case "3": {
      return `<line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 1.5}cm"
            y2="${2 + y * 0.5}cm"
          />`;
    }
    case "4": {
      return `<line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y2="${2 + y * 1.5}cm"
            y1="${2 + y * 0.5}cm"
          />`;
    }
    case "5": {
      return `<line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 1.5}cm"
            y2="${2 + y * 1.5}cm"
          />
          <line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y2="${2 + y * 1.5}cm"
            y1="${2 + y * 0.5}cm"
          />`;
    }
    case "6": {
      return `<line
            x1="${1.5 + x}cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 1.5}cm"
            y2="${2 + y * 0.5}cm"
          />`;
    }
    case "7": {
      return `<line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 1.5}cm"
            y2="${2 + y * 1.5}cm"
          />
          <line
            x1="${1.5 + x}cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 1.5}cm"
            y2="${2 + y * 0.5}cm"
          />`;
    }
    case "8": {
      return `<line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 0.5}cm"
            y2="${2 + y * 0.5}cm"
          />
          <line
            x1="${1.5 + x}cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 1.5}cm"
            y2="${2 + y * 0.5}cm"
          />`;
    }
    case "9": {
      return `<line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 0.5}cm"
            y2="${2 + y * 0.5}cm"
          />
          <line
            x1="${1.5 + x}cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 1.5}cm"
            y2="${2 + y * 0.5}cm"
          />
          <line
            x1="1.5cm"
            x2="${1.5 + x}cm"
            y1="${2 + y * 1.5}cm"
            y2="${2 + y * 1.5}cm"
          />`;
    }
  }

  return "";
}

export const Numeral = (props: DigitProps) => {
  const value = props.value.padStart(4, "0");
  console.assert(value.length === 4);
  if (value === "0000") return null;
  const [n1, n2, n3, n4] = value.split("");
  const width = props.width ?? "3cm";
  const height = props.height ?? "4cm";
  const scale = props.scale ?? 1;

  const src = `data:image/svg+xml,<svg
  xmlns="http://www.w3.org/2000/svg"
  width="${width}"
  height="${height}"
  stroke="currentColor"
  stroke-linejoin="round"
  stroke-linecap="${props.strokeLinecap ?? "round"}"
  stroke-width="${props.strokeWidth}"
>
  <title>
    The number ${value} represented as a Cistercian Monk numeral
  </title>
  <g transform="scale(${scale} ${scale})">
  <line x1="1.5cm" x2="1.5cm" y1="0.5cm" y2="3.5cm" />
  ${svgStrForVal(n4, "ones")}
  ${svgStrForVal(n3, "tens")}
  ${svgStrForVal(n2, "hundreds")}
  ${svgStrForVal(n1, "thousands")}
  </g>
</svg>`;

  return (
    // eslint-disable-next-line @next/next/no-img-element
    <Image
      height={height}
      width={width}
      src={src}
      alt={`The number ${value} represented as a Cistercian Monk numeral`}
    />
  );
};

// src/routes/fonts/cistercian-monk-numerals/Numeral.svelte
<script lang="ts">
  export let value: string;
  export let strokeLinecap: 'round' | 'inherit' | 'butt' | 'square' = 'round';
  export let strokeWidth: number;
  export let width = '3cm';
  export let height = '4cm';
  export let scale = 1;

  let svg: SVGSVGElement;

  $: paddedValue = value.padStart(4, '0');
  // $: [n1, n2, n3, n4] = paddedValue.split('');

  const MAG = [
    { x: -1, y: 1 }, // thousands
    { x: 1, y: 1 }, // hundreds
    { x: -1, y: -1 }, // tens
    { x: 1, y: -1 } // ones
  ];

  function save() {
    const svgData = new XMLSerializer().serializeToString(svg);
    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    const svgUrl = URL.createObjectURL(svgBlob);
    const downloadLink = document.createElement('a');
    downloadLink.href = svgUrl;
    downloadLink.download = `cistercian-monk-numeral-${value}.svg`;
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);
  }
</script>

<svg
  xmlns="http://www.w3.org/2000/svg"
  {width}
  {height}
  stroke="currentColor"
  stroke-linejoin="round"
  stroke-linecap={strokeLinecap}
  stroke-width={strokeWidth}
  bind:this={svg}
  on:click={save}
  on:keypress={(e) => {
    if (e.key === 'Enter') {
      save();
    }
  }}
>
  <title>The number {value} represented as a Cistercian Monk numeral</title>
  <g transform="scale({scale} {scale})">
    {#if paddedValue !== '0000'}
      <line x1="1.5cm" x2="1.5cm" y1="0.5cm" y2="3.5cm" />
      {#each paddedValue.split('') as n, i}
        {#if n === '1' || n === '5' || n === '7' || n === '9'}
          <line
            x1="1.5cm"
            x2="{1.5 + MAG[i].x}cm"
            y1="{2 + MAG[i].y * 1.5}cm"
            y2="{2 + MAG[i].y * 1.5}cm"
          />
        {/if}
        {#if n === '2' || n === '8' || n === '9'}
          <line
            x1="1.5cm"
            x2="{1.5 + MAG[i].x}cm"
            y1="{2 + MAG[i].y * 0.5}cm"
            y2="{2 + MAG[i].y * 0.5}cm"
          />
        {/if}
        {#if n === '3'}
          <line
            x1="1.5cm"
            x2="{1.5 + MAG[i].x}cm"
            y1="{2 + MAG[i].y * 1.5}cm"
            y2="{2 + MAG[i].y * 0.5}cm"
          />
        {/if}
        {#if n === '4' || n === '5'}
          <line
            x1="1.5cm"
            x2="{1.5 + MAG[i].x}cm"
            y2="{2 + MAG[i].y * 1.5}cm"
            y1="{2 + MAG[i].y * 0.5}cm"
          />
        {/if}
        {#if n === '6' || n === '7' || n === '8' || n === '9'}
          <line
            x1="{1.5 + MAG[i].x}cm"
            x2="{1.5 + MAG[i].x}cm"
            y1="{2 + MAG[i].y * 1.5}cm"
            y2="{2 + MAG[i].y * 0.5}cm"
          />
        {/if}
      {/each}
    {:else}
      <rect x="1cm" y="0.5cm" width="1.5cm" height="2.5cm" rx="1.5cm" ry="1cm" fill="none" />
    {/if}
  </g>
</svg>

<style>
  svg {
    cursor: copy;
  }
</style>
