// src/lib/components/Store/ThumbnailGallery.svelte
<script lang="ts">
  export let images: string[];
  $: imageIndex = 0;
  const maxIndex = images.length - 1;

  if (images.length == 0) {
    throw Error('must pass at least one image to Thumbnail Gallery!');
  }

  const nextImageIndex = () => {
    if (imageIndex < maxIndex) {
      imageIndex = imageIndex + 1;
    } else {
      imageIndex = 0;
    }
  };
  const previousImageIndex = () => {
    if (imageIndex == 0) {
      imageIndex = maxIndex;
    } else {
      imageIndex = imageIndex - 1;
    }
  };
</script>

<div class="gallery">
  <img alt="a product thumbnail" src={images[imageIndex]} />
  <button class="index-button left" on:click={previousImageIndex}> &#706; </button>
  <button class="new-tab-button" on:click={() => window.open(images[imageIndex])} />
  <button class="index-button right" on:click={nextImageIndex}> &#707; </button>
</div>

<style>
  .gallery {
    position: relative;
  }

  img {
    height: auto;
    max-width: 100%;
  }

  .index-button {
    position: absolute;
    width: 30%;
    top: 0;
    bottom: 0;
    background: transparent;
    border: none !important;
    font-size: 0;
  }

  .index-button.left {
    left: 0;
    cursor: url('/left-arrow.cur'), pointer;
  }

  .index-button.right {
    right: 0;
    cursor: url('/right-arrow.cur'), pointer;
  }

  .new-tab-button {
    position: absolute;
    left: 30%;
    right: 30%;
    width: 40%;
    top: 0;
    bottom: 0;
    background: transparent;
    border: none !important;
    font-size: 0;
    cursor: zoom-in;
  }
</style>

// components/Store/ThumbnailGallery.tsx
import styles from "./ThumbnailGallery.module.css";
import { useState } from "react";
import Image, { StaticImageData } from "next/image";

interface Props {
  images: (string | StaticImageData)[];
}

export const ThumbnailGallery: React.FC<Props> = ({ images }) => {
  if (images.length == 0) {
    throw Error("must pass at least one image to Thumbnail Gallery!");
  }

  const maxIndex = images.length - 1;
  const [imageIndex, setImageIndex] = useState(0);
  const nextImageIndex = () => {
    if (imageIndex < maxIndex) {
      setImageIndex(imageIndex + 1);
    } else {
      setImageIndex(0);
    }
  };
  const previousImageIndex = () => {
    if (imageIndex == 0) {
      setImageIndex(maxIndex);
    } else {
      setImageIndex(imageIndex - 1);
    }
  };

  return (
    <div className={styles.gallery}>
      <Image
        alt="a product thumbnail"
        src={images[imageIndex]}
        style={{ height: "auto", maxWidth: "100%" }}
      />
      <button
        className={[styles.indexButton, styles.left].join(" ")}
        onClick={previousImageIndex}
      >
        &#706;
      </button>
      <button
        className={[styles.indexButton, styles.right].join(" ")}
        onClick={nextImageIndex}
      >
        &#707;
      </button>
    </div>
  );
};
